package com.huanfran.buildingessentials.graphics.gl.enumeration

import com.huanfran.buildingessentials.graphics.gl.enumeration.identification.GLTarget
import org.lwjgl.opengl.GL46C

enum class BufferTarget(val id: Int) : GLTarget {


    ARRAY_BUFFER(GL46C.GL_ARRAY_BUFFER),

    ELEMENT_ARRAY_BUFFER(GL46C.GL_ELEMENT_ARRAY_BUFFER),

    PIXEL_PACK_BUFFER(GL46C.GL_PIXEL_PACK_BUFFER),

    PIXEL_UNPACK_BUFFER(GL46C.GL_PIXEL_UNPACK_BUFFER),

    TRANSFORM_FEEDBACK_BUFFER(GL46C.GL_TRANSFORM_FEEDBACK_BUFFER),

    UNIFORM_BUFFER(GL46C.GL_UNIFORM_BUFFER),

    TEXTURE_BUFFER(GL46C.GL_TEXTURE_BUFFER),

    COPY_READ_BUFFER(GL46C.GL_COPY_READ_BUFFER),

    COPY_WRITE_BUFFER(GL46C.GL_COPY_WRITE_BUFFER),

    DRAW_INDIRECT_BUFFER(GL46C.GL_DRAW_INDIRECT_BUFFER),

    ATOMIC_COUNTER_BUFFER(GL46C.GL_ATOMIC_COUNTER_BUFFER),

    DISPATCH_INDIRECT_BUFFER(GL46C.GL_DISPATCH_INDIRECT_BUFFER),

    SHADER_STORAGE_BUFFER(GL46C.GL_SHADER_STORAGE_BUFFER),

    PARAMETER_BUFFER(GL46C.GL_PARAMETER_BUFFER);


}