package com.huanfran.buildingessentials.graphics.gl.enumeration

import org.lwjgl.opengl.GL46C

enum class DrawMode(val id: Int){


    POINTS(GL46C.GL_POINTS),

    LINE_STRIP(GL46C.GL_LINE_STRIP),

    LINE_LOOP(GL46C.GL_LINE_LOOP),

    LINES(GL46C.GL_LINES),

    TRIANGLE_STRIP(GL46C.GL_TRIANGLE_STRIP),

    TRIANGLE_FAN(GL46C.GL_TRIANGLE_FAN),

    TRIANGLES(GL46C.GL_TRIANGLES),

    LINES_ADJACENCY(GL46C.GL_LINES_ADJACENCY),

    LINE_STRIP_ADJACENCY(GL46C.GL_LINE_STRIP_ADJACENCY),

    TRIANGLES_ADJACENCY(GL46C.GL_TRIANGLES_ADJACENCY),

    TRIANGLE_STRIP_ADJACENCY(GL46C.GL_TRIANGLE_STRIP_ADJACENCY),

    PATCHES(GL46C.GL_PATCHES);


}