package com.huanfran.buildingessentials.graphics.gl.enumeration

import org.lwjgl.opengl.GL30
import org.lwjgl.opengl.GL46C

enum class TextureDataFormat(val id: Int) {


    RED(GL46C.GL_RED),

    GREEN(GL46C.GL_GREEN),

    BLUE(GL46C.GL_BLUE),

    ALPHA(GL46C.GL_ALPHA),

    RG(GL46C.GL_RG),

    RGB(GL46C.GL_RGB),

    RGBA(GL46C.GL_RGBA),

    BGR(GL46C.GL_BGR),

    BGRA(GL46C.GL_BGRA),

    RED_INTEGER(GL46C.GL_RED_INTEGER),

    GREEN_INTEGER(GL46C.GL_GREEN_INTEGER),

    BLUE_INTEGER(GL46C.GL_BLUE_INTEGER),

    ALPHA_INTEGER(GL30.GL_ALPHA_INTEGER),

    RG_INTEGER(GL46C.GL_RG_INTEGER),

    RGB_INTEGER(GL46C.GL_RGB_INTEGER),

    RGBA_INTEGER(GL46C.GL_RGBA_INTEGER),

    BGR_INTEGER(GL46C.GL_BGR_INTEGER),

    BGRA_INTEGER(GL46C.GL_BGRA_INTEGER),

    STENCIL_INDEX(GL46C.GL_STENCIL_INDEX),

    DEPTH_COMPONENT(GL46C.GL_DEPTH_COMPONENT),

    DEPTH_STENCIL(GL46C.GL_DEPTH_STENCIL);


}